### ISSUE TITLE
分版块建议

### ISSUE THREAD

**Issue by wangzhenyujiang** [namehub/namehub#1]
建议分不同的版块比如 iOS 板块，安卓板块，PHP 板块..............................(此处省略一万字).........................你懂得！考虑这样的原因是这样便于用户查阅和 PR 自己擅长的领域。

**Comment by keyfunc** [comment]
其实 只是命名的话 和 语言之类的没太大关系，和使用场景有关，使用场景的话用Tag我觉得应该就能区分了。

**Comment by keyfunc** [comment]
如果Tag区分起来太麻烦的话，看情况会创建几个文件夹来区分的

**Comment by shnode** [comment]
你好，我想加入这个组织，一起维护。

**Comment by keyfunc** [comment]
@shnode 已邀请

**Comment by silvernoo** [comment]
建议放到wiki里维护吧

**Comment by augustyip** [comment]
for your ref:

http://namingschemes.com/

**Comment by chinaboard** [comment]
放到wiki里维护好主意，求邀请
